name: CI

on:
  push:
jobs:
  pipelines:
    runs-on: ubuntu-latest
    environment: CI
    env:
      INFURA_API_KEY: ${{ secrets.INFURA_API_KEY }}
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
      ETHERSCAN_KEY: ${{ secrets.ETHERSCAN_KEY }}
      ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_API_KEY }}
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup
        run: yarn

      - name: Build(to JS)
        run: yarn build

      - name: Lint Solidity
        run: yarn lint:sol

      - name: Test
        run: yarn test
