name: CI
on:
    push:
    pull_request:
jobs:
    pipelines:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [ 14.x ]
        steps:
            -   uses: actions/checkout@v2
            -   name: Use Node.js ${{ matrix.node-version }}
                uses: actions/setup-node@v1
                with:
                    node-version: ${{ matrix.node-version }}
            -   name: Setup
                run: |
                    yarn
            -   name: Build(to JS)
                run: |
                    yarn build
            -   name: Lint Solidity
                run: |
                    yarn lint:sol
            -   name: Test
                run: |
                    yarn test
